"use client";

import { usePresentationPreferences } from "@/components/providers/presentation-provider";
import { EmptyState } from "@/components/ui/empty-state";
import { OperationsPageHeader } from "@/components/ui/operations-page-header";
import { StatusLabel, type StatusTone } from "@/components/ui/status-label";
import type { PolicyStatus, PolicySummary } from "@/domain/policies/policy";
import { AlertTriangle, BookOpen, CalendarClock, Plus, Search, SlidersHorizontal } from "lucide-react";
import { WorkspaceLink as Link } from "@/components/navigation/workspace-link";
import { formatDateTime } from "@/lib/presentation-format";
import { useMemo, useState } from "react";

export const policyStatusPresentation: Record<PolicyStatus, { label: string; tone: StatusTone }> = {
  draft: { label: "Draft", tone: "neutral" }, in_review: { label: "In review", tone: "info" }, published: { label: "Published", tone: "success" }, scheduled: { label: "Scheduled", tone: "info" }, retired: { label: "Retired", tone: "neutral" }, expired: { label: "Expired", tone: "danger" }, conflicting: { label: "Conflict", tone: "warning" }, parsing_failed: { label: "Source needs attention", tone: "danger" },
};

export function PolicyLibrary({ policies, sourceLabel, canManage = false }: { policies: readonly PolicySummary[]; sourceLabel: string; canManage?: boolean }) {
  const presentation = usePresentationPreferences();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<PolicyStatus | "all">("all");
  const rows = useMemo(() => { const normalized = query.trim().toLocaleLowerCase(); return policies.filter((item) => (!normalized || [item.id, item.title, item.description, item.owner.name, ...item.appliesTo].join(" ").toLocaleLowerCase().includes(normalized)) && (status === "all" || item.status === status)); }, [policies, query, status]);
  const metrics = { published: policies.filter((item) => item.status === "published").length, review: policies.filter((item) => item.status === "in_review" || item.status === "draft").length, issues: policies.filter((item) => ["conflicting", "parsing_failed", "expired"].includes(item.status)).length, scheduled: policies.filter((item) => item.status === "scheduled").length };
  const emptyState = policies.length ? <EmptyState icon={SlidersHorizontal} title="No policies match this view" description="Reset the search and status filter to see all policies." action={<button type="button" onClick={() => { setQuery(""); setStatus("all"); }} className="text-sm font-semibold text-action hover:underline">Reset filters</button>} /> : <EmptyState icon={BookOpen} title="No policies yet" description="Published rules and draft policy changes will appear here." />;
  return <div className="min-h-[calc(100vh-60px)] bg-surface"><OperationsPageHeader title="Policies" description="Published rules, draft changes, and policy health." meta={sourceLabel} actions={canManage ? <Link href="/policies/new" className="inline-flex h-10 items-center gap-2 rounded-md bg-action px-4 text-sm font-semibold text-white hover:bg-action-strong"><Plus aria-hidden="true" size={16} />New policy</Link> : undefined} /><section aria-label="Policy summary" className="border-b border-border bg-canvas/55 px-4 sm:px-6 lg:px-7"><dl className="mx-auto grid max-w-[1540px] grid-cols-2 divide-x divide-border md:grid-cols-4">{[
    { label: "Published", value: metrics.published, icon: BookOpen, tone: "text-success" }, { label: "Draft or review", value: metrics.review, icon: CalendarClock, tone: "text-info" }, { label: "Needs attention", value: metrics.issues, icon: AlertTriangle, tone: "text-danger" }, { label: "Scheduled", value: metrics.scheduled, icon: CalendarClock, tone: "text-secondary" },
  ].map((item) => { const Icon = item.icon; return <div key={item.label} className="flex min-h-[88px] items-center gap-3 px-3 first:pl-0 md:px-6 md:first:pl-0"><Icon aria-hidden="true" size={20} className={item.tone} /><div><dt className="text-xs text-secondary">{item.label}</dt><dd className="mt-0.5 text-xl font-semibold text-primary">{item.value}</dd></div></div>; })}</dl></section>
    <div className="mx-auto max-w-[1540px] px-4 py-6 sm:px-6 lg:px-7"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1 sm:max-w-[620px]"><span className="sr-only">Search policies</span><Search aria-hidden="true" size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles, owners, or case types" className="h-10 w-full rounded-md border border-border pl-10 pr-3 text-sm outline-none focus:border-focus" /></label><label className="sm:ml-auto"><span className="sr-only">Filter policy status</span><select value={status} onChange={(event) => setStatus(event.target.value as PolicyStatus | "all")} className="h-10 rounded-md border border-border bg-surface px-3 text-sm"><option value="all">All statuses</option>{Object.entries(policyStatusPresentation).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select></label></div>
      <div className="mt-5 overflow-hidden border border-border"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] border-collapse text-left"><caption className="sr-only">Policy library</caption><thead className="bg-canvas/65 text-[11px] font-semibold uppercase text-muted"><tr className="border-b border-border"><th className="px-4 py-3">Policy</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Applies to</th><th className="px-3 py-3">Owner</th><th className="px-3 py-3">Active dates</th><th className="px-3 py-3">Source</th><th className="px-4 py-3">Usage</th></tr></thead><tbody className="divide-y divide-border">{rows.map((item) => { const state = policyStatusPresentation[item.status]; return <tr key={item.id} className="group hover:bg-[#f2f8f7]"><td className="max-w-[320px] px-4 py-4"><Link href={`/policies/${item.id}`} className="text-sm font-semibold text-primary group-hover:text-action">{item.title}</Link><p className="mt-1 text-xs leading-5 text-secondary">{item.description}</p><p className="mt-1 font-mono text-[11px] text-muted">{item.id} / v{item.currentVersion}</p></td><td className="px-3 py-4"><StatusLabel tone={state.tone}>{state.label}</StatusLabel>{item.health !== "healthy" ? <p className="mt-2 text-[11px] capitalize text-warning">{item.health.replaceAll("_", " ")}</p> : null}</td><td className="px-3 py-4 text-xs leading-5 text-secondary">{item.appliesTo.join(", ")}</td><td className="px-3 py-4 text-sm text-secondary">{item.owner.name}</td><td className="px-3 py-4 text-xs text-secondary">{item.effectiveFrom ? formatDateTime(item.effectiveFrom, presentation, { dateStyle: "medium" }) : "Not active"}<br />{item.effectiveTo ? `to ${formatDateTime(item.effectiveTo, presentation, { dateStyle: "medium" })}` : item.effectiveFrom ? "No end date" : ""}</td><td className="px-3 py-4"><p className="text-xs capitalize text-primary">{item.source.kind}</p><p className="mt-1 max-w-[180px] truncate text-[11px] text-muted">{item.source.name}</p></td><td className="px-4 py-4 text-sm tabular-nums text-secondary">{item.usedByCases} cases</td></tr>; })}</tbody></table></div>{!rows.length ? emptyState : <footer className="flex min-h-12 items-center border-t border-border px-4 text-xs text-muted">Showing {rows.length} of {policies.length} policies</footer>}</div>
    </div></div>;
}
